{% set name = "lmoments3" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmoments3-{{ version }}.tar.gz
  sha256: 52f1de98c23930a1ab694bfb6077da3fc99a787751f6c395f0179a99314dd3fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy

test:
  imports:
    - lmoments3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ouranosinc/lmoments3
  summary: Estimate linear moments for statistical distribution functions.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
    - aulemahal
