{% set name = "lmoments3" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lmoments3-{{ version }}.tar.gz
  sha256: bb58bfc23c924ebe30852b57a9ac4fe15549bf9376843b7ab67aed79bc06bee1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm >=8.0
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - lmoments3
  commands:
    - pip check
    # Requires that the `tests` folder be included in source files 
    # - python -m unittest discover -v
  requires:
    - pip
  # source_files:
    # - lmoments3/tests
    - python {{ python_min }}

about:
  home: https://github.com/Ouranosinc/lmoments3
  summary: Estimate linear moments for statistical distribution functions.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
    - aulemahal
