{% set name = "lmoments3" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lmoments3-{{ version }}.tar.gz
  sha256: cdbba3f183feede8422e85e9a99732bd14d5e19b9f0db87315c24343cb524748

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - versioneer
  run:
    - python >=3.8
    - numpy
    - scipy

test:
  imports:
    - lmoments3
  commands:
    - pip check
    - python -m unittest discover -v
  requires:
    - pip
  source_files:
    - lmoments3
    - tests

about:
  home: https://github.com/Ouranosinc/lmoments3
  summary: Estimate linear moments for statistical distribution functions.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
    - aulemahal
